DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM
(
    Room_Id         INTEGER PRIMARY KEY AUTO_INCREMENT,
    Room_Number     INTEGER NOT NULL UNIQUE ,
    Count_Of_Places INTEGER NOT NULL,
    Room_Class      VARCHAR(30) NOT NULL
);