DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM
(
    ROOM_ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    ROOM_NUMBER     INTEGER NOT NULL UNIQUE ,
    COUNT_OF_PLACES INTEGER NOT NULL,
    ROOM_CLASS      VARCHAR(30) NOT NULL
);